# Generated by Django 3.0.7 on 2020-06-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200)),
                ('cate_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_phone', models.CharField(max_length=200)),
                ('cus_address', models.CharField(max_length=200)),
                ('cus_username', models.CharField(max_length=50)),
                ('cus_password', models.CharField(max_length=16)),
                ('cus_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_date', models.DateTimeField(auto_now_add=True)),
                ('ord_price', models.IntegerField(default=0)),
                ('cus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_descripton', models.TextField()),
                ('pro_price', models.IntegerField(default=0)),
                ('pro_active', models.BooleanField(default=True)),
                ('pro_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_price', models.IntegerField(default=0)),
                ('ord_quanlity', models.IntegerField(default=1)),
                ('ord_discount', models.IntegerField(default=0)),
                ('ord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
                ('pro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Products')),
            ],
        ),
    ]
